// Hand-authored layer: facts no package provides.
// trivia: 5 durable facts per country. Numbers come from data sources, not here.

const trivia = {
  // ---- Africa ----
  AGO: ["Largest Portuguese-speaking country by area.", "Oil and diamonds dominate its economy.", "Luanda has ranked among the most expensive cities in the world for expatriates.", "The giant sable antelope, found only here, is a national symbol once feared extinct.", "Portuguese dominates daily life more than in almost any other African state."],
  BDI: ["Moved its political capital to Gitega in 2019.", "Economy relies heavily on coffee and tea exports.", "One of the most densely populated countries in mainland Africa.", "Its royal drumming tradition is on UNESCO's intangible heritage list.", "Lake Tanganyika on its border is the world's second-deepest lake."],
  BEN: ["Birthplace of the Vodun (Voodoo) religion.", "Once the powerful Kingdom of Dahomey.", "The Dahomey Amazons were an all-female military regiment.", "The stilt village of Ganvié is called the 'Venice of Africa'.", "Ouidah's 'Door of No Return' memorializes the slave trade."],
  BFA: ["Its name means 'Land of Incorruptible People'.", "Hosts FESPACO, Africa's largest film festival.", "Renamed from Upper Volta in 1984 by Thomas Sankara.", "The Ruins of Loropéni are its first UNESCO World Heritage Site.", "One of the world's largest cotton producers."],
  BWA: ["One of the world's largest diamond producers.", "Home to much of the Okavango Delta and Kalahari.", "Its currency, the pula, means 'rain'.", "Hosts the world's largest population of African elephants.", "Went from one of the poorest nations to upper-middle income on diamonds."],
  CAF: ["Landlocked and rich in diamonds and uranium.", "Among the least developed countries despite its resources.", "Sits almost exactly at the center of the African continent.", "Emperor Bokassa staged a bankrupting coronation in 1977.", "Dzanga-Sangha is a famed gathering site for forest elephants."],
  CIV: ["World's largest cocoa producer.", "Yamoussoukro holds one of the world's largest churches.", "The Basilica of Our Lady of Peace is among the world's largest churches.", "The capital moved from Abidjan to Yamoussoukro in 1983.", "Abidjan is one of the largest French-speaking cities on Earth."],
  CMR: ["Called 'Africa in miniature' for its diversity.", "Officially bilingual in French and English.", "Mount Cameroon is an active volcano and a regional high point.", "Its football team was the first African side to reach a World Cup quarterfinal (1990).", "Tensions between English- and French-speaking regions have driven recent conflict."],
  COD: ["Second-largest country in Africa by area.", "Holds vast reserves of battery-grade cobalt.", "The Congo is the world's deepest river.", "Home to bonobos, found in the wild nowhere else.", "Four national languages sit alongside official French."],
  COG: ["Straddles the equator and is heavily forested.", "Oil is the backbone of its economy.", "Often called 'Congo-Brazzaville' to distinguish it from its neighbor.", "Shares the Congolese rumba heritage with the DRC.", "Nouabalé-Ndoki is one of the least disturbed rainforests on Earth."],
  COM: ["Volcanic archipelago in the Indian Ocean.", "A top global producer of ylang-ylang for perfume.", "Has seen more than 20 coups or attempts since 1975.", "Its name derives from the Arabic for 'moon'.", "The 'living fossil' coelacanth was rediscovered in its waters."],
  CPV: ["Volcanic island nation off West Africa.", "Birthplace of the morna music genre.", "Cesária Évora, the 'Barefoot Diva', brought its music worldwide.", "More Cape Verdeans live abroad than on the islands.", "It was uninhabited before Portuguese settlement in the 15th century."],
  DJI: ["Hosts foreign military bases from several powers.", "Lake Assal is among the saltiest waters on Earth.", "Lake Assal is the lowest point in Africa.", "Its port is a vital gateway for landlocked Ethiopia.", "It guards the strategic Bab-el-Mandeb strait."],
  DZA: ["Largest country in Africa by area.", "Over 80% is covered by the Sahara Desert.", "The Tassili n'Ajjer plateau holds ancient rock art.", "It won a long, brutal war of independence from France in 1962.", "Natural gas makes it a major energy supplier to Europe."],
  EGY: ["Building a new administrative capital east of Cairo.", "The Nile is generally considered Earth's longest river.", "The Great Pyramid is the only surviving ancient wonder.", "The Suez Canal carries a large share of global shipping.", "Most Egyptians live on a few percent of the land, along the Nile."],
  ERI: ["Gained independence from Ethiopia in 1993.", "Asmara is noted for its Italian modernist architecture.", "Asmara's modernist core is a UNESCO World Heritage Site.", "It has one of the longest national-service systems anywhere.", "The Dahlak Archipelago is a remote Red Sea diving spot."],
  ESH: ["A disputed territory largely controlled by Morocco.", "Claimed by the Sahrawi Arab Democratic Republic.", "Morocco built a 2,700-km sand berm dividing the territory.", "It is Africa's largest territory without full recognition as a state.", "Phosphate and Atlantic fishing waters fuel the dispute."],
  ETH: ["One of few African nations never formally colonized.", "Uses a unique 13-month calendar.", "Its calendar runs about seven to eight years behind the Gregorian.", "Coffee is believed to have originated in its Kaffa region.", "The famous early-hominid fossil 'Lucy' was found here."],
  GAB: ["Nearly 90% covered by rainforest.", "Created 13 national parks to boost ecotourism.", "Straddles the equator on the Atlantic coast.", "Loango is famous for beach-going elephants and hippos.", "Oil gives it one of the region's higher per-capita incomes."],
  GHA: ["First sub-Saharan nation to gain independence (1957).", "Lake Volta is among the world's largest reservoirs by area.", "Named after a medieval West African empire.", "Birthplace of pan-Africanism under Kwame Nkrumah.", "The Ashanti golden stool remains a powerful symbol."],
  GIN: ["Holds a huge share of the world's bauxite reserves.", "The Niger River rises in its highlands.", "The only French colony to vote for immediate independence in 1958.", "Mount Nimba's reserve is a UNESCO World Heritage Site.", "Several major West African rivers rise in its highlands."],
  GMB: ["Smallest country in mainland Africa.", "Almost entirely surrounded by Senegal.", "Essentially follows the course of the Gambia River.", "Alex Haley's 'Roots' traced his ancestry to a village here.", "It was briefly joined with Senegal as Senegambia."],
  GNB: ["Former Portuguese colony.", "Cashews dominate its exports.", "The Bijagós Archipelago is a UNESCO biosphere reserve.", "It has endured chronic instability since independence.", "One of the world's most cashew-dependent economies."],
  GNQ: ["Only African country with Spanish as an official language.", "Oil-rich but with stark inequality.", "Its capital, Malabo, sits on a volcanic island.", "One of Africa's smallest countries by population.", "Oil wealth contrasts with low human-development scores."],
  KEN: ["Famous for the Great Rift Valley and Maasai Mara.", "A long-distance running powerhouse.", "The Great Wildebeest Migration crosses the Maasai Mara yearly.", "Nairobi National Park borders the city skyline.", "A pioneer of mobile money via M-Pesa."],
  LBR: ["Founded by freed American slaves in the 1800s.", "Its flag closely resembles the US flag.", "Africa's oldest modern republic, founded in 1847.", "Ellen Johnson Sirleaf was Africa's first elected female head of state.", "Its ship registry is among the world's largest."],
  LBY: ["Over 90% desert.", "Holds Africa's largest proven oil reserves.", "Leptis Magna is among the best-preserved Roman cities.", "The Great Man-Made River pipes aquifer water across the desert.", "Muammar Gaddafi ruled for over four decades."],
  LSO: ["Entirely surrounded by South Africa.", "Its lowest point is the highest of any country.", "One of only three states entirely surrounded by another.", "It sells water to South Africa via a highlands project.", "The Basotho blanket is a distinctive national garment."],
  MAR: ["Home to the world's oldest operating university.", "Where the Sahara meets the Atlas Mountains.", "The blue-washed town of Chefchaouen is a famous sight.", "Set to co-host the 2030 FIFA World Cup.", "Fez has one of the world's largest car-free urban areas."],
  MDG: ["World's fourth-largest island.", "About 90% of its wildlife is found nowhere else.", "Lemurs live in the wild only here.", "Its avenue of giant baobabs is an iconic sight.", "Its people have mixed African and Austronesian ancestry."],
  MLI: ["Timbuktu was a medieval center of learning.", "Largely covered by the Sahara.", "The Great Mosque of Djenné is the largest mud-brick building.", "Medieval emperor Mansa Musa is often called history's richest person.", "Renowned for desert blues and the kora harp."],
  MOZ: ["Its flag features an AK-47.", "Long Indian Ocean coastline with coral reefs.", "Portuguese is the official language.", "The Bazaruto Archipelago is a marine national park.", "Its long civil war ended in 1992."],
  MRT: ["One of the last countries to abolish slavery (1981).", "Mostly Saharan desert.", "Its 'iron ore train' is among the longest and heaviest.", "Chinguetti holds historic desert Islamic libraries.", "The 'Eye of the Sahara' is visible from space."],
  MUS: ["Was the only known home of the extinct dodo.", "A multicultural Indian Ocean island.", "Had no native land mammals before humans arrived.", "Mark Twain quoted that heaven was copied after it.", "Creole, French, and English mix in daily life."],
  MWI: ["Lake Malawi holds more fish species than any other lake.", "Known as the 'Warm Heart of Africa'.", "Lake Malawi covers about a third of the country.", "One of the least urbanized African nations.", "Explorer David Livingstone helped map the region."],
  NAM: ["Home to the Namib, considered the world's oldest desert.", "One of the most sparsely populated countries.", "The dunes of Sossusvlei are among the world's highest.", "The Skeleton Coast is littered with shipwrecks.", "It was among the first to put conservation in its constitution."],
  NER: ["Among the world's largest uranium producers.", "One of the hottest countries on Earth.", "Named after the Niger River.", "Its Aïr and Ténéré reserves protect Saharan wildlife.", "It has one of the world's highest birth rates."],
  NGA: ["Most populous country in Africa.", "Nollywood is among the world's largest film industries.", "Lagos is one of the fastest-growing megacities on Earth.", "Home to over 250 ethnic groups and 500 languages.", "Afrobeats has become a global music force."],
  RWA: ["Known as the 'Land of a Thousand Hills'.", "Banned single-use plastic bags.", "Mountain gorilla trekking draws visitors to its volcanoes.", "It rebuilt rapidly after the 1994 genocide.", "Women hold a majority of its parliament's seats."],
  SDN: ["The Nile's main tributaries meet at Khartoum.", "Has more pyramids than Egypt.", "The pyramids of Meroë were built by the Kushite kingdom.", "It was Africa's largest country until South Sudan split off.", "The Blue and White Nile meet at Khartoum."],
  SEN: ["Westernmost country of mainland Africa.", "Dakar long ended the famous off-road rally.", "Gorée Island memorializes the transatlantic slave trade.", "Lake Retba turns pink from salt-loving algae.", "Renowned for mbalax music and Youssou N'Dour."],
  SLE: ["Freetown was founded as a home for freed slaves.", "Rich in diamonds.", "Its name comes from Portuguese for 'Lion Mountains'.", "Freetown has one of the world's largest natural harbors.", "It recovered from a civil war fueled by 'blood diamonds'."],
  SOM: ["Has the longest mainland coastline in Africa.", "Largely ethnically and linguistically homogeneous.", "Has the longest mainland coastline in Africa.", "The breakaway region of Somaliland is a de facto state.", "Frankincense and myrrh have been traded here for millennia."],
  SSD: ["World's youngest widely recognized country (2011).", "Hosts a vast seasonal wildlife migration.", "The Sudd is one of the world's largest wetlands.", "Cattle hold deep cultural and economic value.", "It remains highly oil-dependent and underdeveloped."],
  STP: ["Africa's second-smallest country.", "Volcanic islands straddling the equator.", "Once the world's largest cocoa producer.", "Lies near where the equator meets the prime meridian.", "Uninhabited until Portuguese settlement in the late 1400s."],
  SWZ: ["One of the world's last absolute monarchies.", "Renamed from Swaziland in 2018.", "The Reed Dance is a major annual cultural festival.", "One of the smallest Southern Hemisphere countries.", "Renamed to mark 50 years of independence and avoid confusion with Switzerland."],
  SYC: ["Smallest African country by population.", "Home to the giant coco de mer seed.", "An archipelago of about 115 islands.", "Aldabra Atoll hosts a huge giant-tortoise population.", "Among the highest per-capita incomes in Africa."],
  TCD: ["Lake Chad has shrunk dramatically over decades.", "Landlocked in north-central Africa.", "The Ennedi Plateau's rock art is a UNESCO site.", "Lake Chad was once one of Africa's largest lakes.", "Named after the lake, meaning 'large body of water'."],
  TGO: ["A narrow strip with a short Atlantic coastline.", "Phosphate mining is a key industry.", "The Koutammakou mud tower-houses are a UNESCO site.", "Was a German colony before being split by Britain and France.", "One of the smallest countries in West Africa."],
  TUN: ["Site of ancient Carthage.", "Birthplace of the 2010-11 Arab Spring.", "Star Wars desert scenes were filmed here; 'Tatooine' echoes a town's name.", "Africa's northernmost point lies here.", "The amphitheater at El Djem rivals Rome's Colosseum."],
  TZA: ["Home to Mount Kilimanjaro, Africa's highest peak.", "The Zanzibar archipelago lies off its coast.", "The Serengeti and Ngorongoro Crater are world-famous.", "Swahili is widely spoken across East Africa.", "Olduvai Gorge is a key human-origins site."],
  UGA: ["The White Nile rises at Lake Victoria here.", "Called the 'Pearl of Africa'.", "It shares Lake Victoria, Africa's largest lake.", "Home to roughly half the world's mountain gorillas.", "The equator runs through its south."],
  ZAF: ["Has three capitals across branches of government.", "Has 12 official languages.", "The first human heart transplant was performed in Cape Town in 1967.", "Nelson Mandela became its first democratically elected president in 1994.", "Table Mountain is a Cape Town icon."],
  ZMB: ["Shares Victoria Falls with Zimbabwe.", "Copper drives its economy.", "Named after the Zambezi River.", "Devil's Pool lets the brave swim at Victoria Falls' edge.", "One of the world's most copper-dependent economies."],
  ZWE: ["Named after the Great Zimbabwe ruins.", "Shares Victoria Falls with Zambia.", "It suffered one of history's worst hyperinflations.", "Great Zimbabwe is sub-Saharan Africa's largest ancient stone ruin.", "Home to part of the vast Hwange wildlife reserve."],
  // ---- Americas ----
  ARG: ["Home to Aconcagua, the Americas' highest peak.", "Tango originated in Buenos Aires.", "Patagonia's glaciers like Perito Moreno are major draws.", "Football legends Maradona and Messi are national icons.", "Yerba mate is a near-ubiquitous social drink."],
  ATG: ["Said to have a beach for every day of the year.", "A twin-island Caribbean nation.", "Nelson's Dockyard is a restored Georgian naval base and UNESCO site.", "Barbuda's pink-sand beaches are largely undeveloped.", "Cricket is a national passion."],
  BHS: ["An archipelago of about 700 islands.", "Home to the famous swimming pigs.", "The Andros Barrier Reef is among the world's longest.", "Dean's Blue Hole is one of the deepest ocean blue holes.", "Tourism and offshore finance dominate."],
  BLZ: ["Only Central American country with English official.", "Home to the Great Blue Hole.", "Holds the second-largest barrier reef after Australia's.", "Caracol features Belize's tallest structure, a Maya temple.", "Known as British Honduras until 1973."],
  BOL: ["Has two capitals: Sucre and La Paz.", "Contains Uyuni, the world's largest salt flat.", "Lake Titicaca, the highest navigable lake, is on its border.", "La Paz is among the highest capitals in the world.", "Uyuni holds some of the world's largest lithium reserves."],
  BRA: ["Largest country in South America.", "Holds about 60% of the Amazon rainforest.", "Portuguese sets it apart from its Spanish-speaking neighbors.", "Rio's Carnival is among the world's biggest festivals.", "Won the men's football World Cup a record five times."],
  BRB: ["Became a republic in 2021.", "An early home of rum distillation.", "Birthplace of pop star Rihanna.", "Its name comes from the 'bearded' fig trees sailors saw.", "The most easterly Caribbean island."],
  CAN: ["Second-largest country by area.", "Has the longest coastline of any nation.", "Has more lakes than the rest of the world combined.", "Officially bilingual in English and French.", "The maple leaf and ice hockey are national symbols."],
  CHL: ["One of the world's longest, narrowest countries.", "The Atacama is the driest non-polar desert.", "Home to Easter Island and its giant moai.", "Hosts some of the world's largest telescopes.", "A leading exporter of copper."],
  COL: ["Only South American country on both the Pacific and Caribbean.", "A leading coffee producer.", "The world's largest exporter of emeralds.", "Birthplace of Gabriel García Márquez and magical realism.", "The Caño Cristales river runs in vivid colors."],
  CRI: ["Abolished its standing army in 1948.", "A global leader in biodiversity and ecotourism.", "'Pura vida' is its national motto and greeting.", "Generates almost all electricity from renewables.", "Holds about 5% of the world's biodiversity."],
  CUB: ["Largest island in the Caribbean.", "Famous for cigars and classic American cars.", "Has one of the world's highest doctor-to-population ratios.", "Old Havana is a UNESCO World Heritage Site.", "Son and salsa music originated here."],
  DMA: ["Known as the 'Nature Island'.", "Home to a vast volcanically heated Boiling Lake.", "One of the few homes of the surviving Kalinago people.", "The sisserou parrot on its flag is found only here.", "Its mountainous interior is largely wild rainforest."],
  DOM: ["Shares Hispaniola with Haiti.", "Site of the first permanent European settlement in the Americas.", "Santo Domingo has the oldest cathedral in the Americas.", "Birthplace of merengue and bachata.", "Baseball is the dominant sport."],
  ECU: ["Named for the equator running through it.", "Includes the Galápagos Islands.", "The Galápagos shaped Darwin's theory of evolution.", "Mount Chimborazo's summit is the farthest point from Earth's center.", "The 'Panama hat' actually originates here."],
  GRD: ["Known as the 'Spice Isle' for its nutmeg.", "Among the world's top nutmeg producers.", "Nutmeg appears on its national flag.", "A US-led invasion took place here in 1983.", "An underwater sculpture park doubles as a reef."],
  GTM: ["Heartland of the ancient Maya civilization.", "Has more than 30 volcanoes.", "Tikal's temples rise above the rainforest.", "Lake Atitlán fills a collapsed volcanic caldera.", "It has the largest indigenous population share in Central America."],
  GUY: ["Only South American country with English official.", "Recent major offshore oil discoveries.", "Kaieteur is one of the world's most powerful single-drop falls.", "It is culturally tied to the Caribbean.", "Its name means 'land of many waters'."],
  HND: ["Once the original 'banana republic'.", "Home to the Maya site of Copán.", "The Bay Islands are a popular Mesoamerican Reef dive spot.", "Copán's Maya ruins are famed for stone carvings.", "It once had one of the world's highest homicide rates."],
  HTI: ["First nation born from a successful slave revolt (1804).", "Shares Hispaniola with the Dominican Republic.", "The Citadelle Laferrière is a vast mountaintop fortress.", "The first independent nation in Latin America and the Caribbean.", "French and Haitian Creole are official languages."],
  JAM: ["Birthplace of reggae music.", "Produces prized Blue Mountain coffee.", "Usain Bolt and many sprint champions hail from here.", "Bob Marley made reggae a global phenomenon.", "The Blue and John Crow Mountains are a UNESCO site."],
  KNA: ["Smallest country in the Americas.", "A twin-island federation.", "Brimstone Hill Fortress is a UNESCO World Heritage Site.", "A scenic former sugar railway now carries tourists.", "Nevis was the birthplace of Alexander Hamilton."],
  LCA: ["Famous for the twin Pitons volcanic peaks.", "Named after Saint Lucy of Syracuse.", "Has produced two Nobel laureates, remarkable for its size.", "Its Sulphur Springs are billed as a 'drive-in volcano'.", "It changed hands between Britain and France many times."],
  MEX: ["Most populous Spanish-speaking country.", "Origin of chocolate, chili, and the tomato.", "Mexico City sits on the site of Aztec Tenochtitlan.", "Day of the Dead is a UNESCO-recognized tradition.", "Chichen Itza is one of the New Seven Wonders."],
  NIC: ["Largest country in Central America.", "Lake Nicaragua is the region's biggest lake.", "Known as the 'land of lakes and volcanoes'.", "Lake Nicaragua historically held rare freshwater sharks.", "Ometepe island rises from two volcanoes in the lake."],
  PAN: ["The Panama Canal links the Atlantic and Pacific.", "Its economy pivots around the canal.", "The canal uses locks to lift ships across the isthmus.", "The Darién Gap breaks the Pan-American Highway with jungle.", "It uses the US dollar alongside the balboa."],
  PER: ["Home to Machu Picchu and the Inca heartland.", "A center of origin for the potato.", "The Nazca Lines are giant desert geoglyphs.", "Cusco was the Inca Empire's capital.", "It has thousands of native potato varieties."],
  PRY: ["One of two landlocked South American countries.", "The Itaipú Dam is a hydropower giant.", "Guaraní is an official language spoken by most people.", "The Itaipú Dam was long the world's top power generator.", "One of the most thoroughly bilingual nations."],
  SLV: ["Smallest, most densely populated Central American country.", "First to adopt Bitcoin as legal tender.", "Known as the 'Land of Volcanoes'.", "Surfers prize its Pacific point breaks.", "The only Central American country without a Caribbean coast."],
  SUR: ["Smallest sovereign state in South America.", "Dutch is the official language.", "The most forested country in the world by land share.", "A diverse mix of African, Indian, Javanese, and Indigenous roots.", "Its central nature reserve is vast pristine rainforest."],
  TTO: ["Birthplace of the steelpan and calypso.", "Pitch Lake is the largest natural asphalt deposit.", "A birthplace of Carnival traditions exported region-wide.", "Soca and calypso music originated here.", "A major exporter of natural gas and petrochemicals."],
  URY: ["Among the first to legalize cannabis nationwide.", "One of South America's most stable democracies.", "Hosted and won the first football World Cup in 1930.", "Among the highest literacy rates in the Americas.", "Beef and mate are central to its culture."],
  USA: ["Has no official language at the federal level.", "Yellowstone (1872) was the world's first national park.", "The world's largest economy by nominal GDP.", "Its 50 states include far-flung Alaska and Hawaii.", "The Grand Canyon and other parks draw millions yearly."],
  VCT: ["A chain of 32 islands and cays.", "A filming location for Pirates of the Caribbean.", "La Soufrière volcano erupted as recently as 2021.", "The Tobago Cays are a marine park of uninhabited islets.", "Known for arrowroot and yachting tourism."],
  VEN: ["Home to Angel Falls, the world's highest waterfall.", "Holds among the largest oil reserves.", "Angel Falls plunges from a flat-topped tepui.", "Holds the world's largest proven oil reserves.", "Lake Maracaibo sees near-constant lightning storms."],
  // ---- Asia ----
  AFG: ["Landlocked and crossed by the Hindu Kush.", "Long a crossroads of the ancient Silk Road.", "The giant Buddhas of Bamiyan were destroyed in 2001.", "The Wakhan Corridor is a remote panhandle bordering China.", "Lapis lazuli has been mined here for millennia."],
  ARE: ["A federation of seven emirates.", "Home to Burj Khalifa, the world's tallest building.", "Built artificial palm-shaped islands off Dubai.", "Sent the Arab world's first mission to Mars.", "A few decades ago it was desert villages and pearl divers."],
  ARM: ["First state to adopt Christianity (early 4th century).", "Mount Ararat is its national symbol.", "One of the oldest known wineries was found in a cave here.", "Its alphabet, from around 405 AD, is still used.", "Its global diaspora outnumbers its home population."],
  AZE: ["Known as the 'Land of Fire'.", "Borders the landlocked Caspian Sea.", "Baku mixes an ancient old city with flame-shaped towers.", "Much of the capital lies below sea level.", "Unusual numbers of mud volcanoes dot its land."],
  BGD: ["One of the most densely populated countries.", "The Sundarbans hold the largest mangrove forest.", "The Sundarbans shelter the Bengal tiger.", "Its language movement inspired Mother Language Day.", "Its rivers form one of the world's largest deltas."],
  BHR: ["An island nation in the Persian Gulf.", "First Gulf state to discover oil.", "Linked to Saudi Arabia by the King Fahd Causeway.", "The lone 'Tree of Life' grows in the desert with no clear water.", "An ancient center of the Dilmun civilization."],
  BRN: ["Ruled by one of the world's wealthiest monarchs.", "Funded largely by oil and gas.", "The Sultan's palace is among the world's largest residences.", "It sits on the island of Borneo.", "Much of it is still old-growth rainforest."],
  BTN: ["Measures Gross National Happiness.", "Carbon-negative, with mandated forest cover.", "TV and internet were only legalized in 1999.", "The Tiger's Nest monastery clings to a cliff.", "It limited tourism for decades to protect its culture."],
  CHN: ["Among the most populous countries on Earth.", "The Great Wall stretches thousands of kilometers.", "Has the world's longest high-speed rail network.", "Invented paper, printing, gunpowder, and the compass.", "The Forbidden City housed emperors for centuries."],
  GEO: ["One of the oldest wine-producing regions.", "Sits at the crossroads of Europe and Asia.", "Wine is still made in buried clay qvevri vessels.", "Its alphabet is one of few unique scripts in use.", "The Caucasus holds some of Europe's highest peaks."],
  IDN: ["World's largest archipelago, 17,000+ islands.", "Most populous Muslim-majority country.", "Sits on the volcanic Pacific 'Ring of Fire'.", "Komodo dragons live in the wild only here.", "Its motto is 'Unity in Diversity'."],
  IND: ["Most populous country in the world.", "Has 22 officially scheduled languages.", "The Taj Mahal was built as a royal mausoleum.", "The concept of zero was developed here.", "Its film industry makes more movies than any other."],
  IRN: ["Heir to the ancient Persian Empire.", "Among the largest holders of natural gas.", "Persepolis was the ceremonial Persian capital.", "Its ancient qanat water channels are an engineering marvel.", "Persian carpets are a centuries-old art."],
  IRQ: ["Mesopotamia, the 'cradle of civilization'.", "The Tigris and Euphrates run through it.", "Writing and the wheel emerged in ancient Mesopotamia.", "Babylon and its legendary gardens lay here.", "The Code of Hammurabi originated here."],
  ISR: ["Has a very high rate of startups per capita.", "The Dead Sea shore is Earth's lowest land point.", "Jerusalem is holy to three major religions.", "The Dead Sea is so salty swimmers float.", "It pioneered drip irrigation and desalination."],
  JOR: ["Home to the rock-carved city of Petra.", "Borders the famously buoyant Dead Sea.", "Wadi Rum doubles as a Mars film set.", "It hosts many refugees relative to its size.", "Petra was carved by the ancient Nabataeans."],
  JPN: ["Made up of roughly 14,000 islands.", "Has one of the world's longest life expectancies.", "Mount Fuji is its sacred, iconic peak.", "The shinkansen pioneered high-speed rail.", "It has the world's oldest monarchy by tradition."],
  KAZ: ["World's largest landlocked country.", "Hosts the Baikonur Cosmodrome for space launches.", "The first human spaceflight launched from Baikonur in 1961.", "The Aral Sea has largely dried up within its borders.", "The ninth-largest country by area."],
  KGZ: ["Over 90% mountainous.", "Issyk-Kul is a vast alpine lake that never freezes.", "The epic of Manas is among the longest oral poems.", "Eagle hunting and other nomadic traditions survive.", "Yurts remain part of rural life."],
  KHM: ["Home to Angkor Wat, the largest religious monument.", "Its flag is the only one to feature a building.", "The Khmer Empire once dominated mainland Southeast Asia.", "It endured the brutal Khmer Rouge in the 1970s.", "Angkor was among the largest pre-industrial cities."],
  KOR: ["A global leader in electronics and shipbuilding.", "Internet speeds rank among the world's fastest.", "K-pop and Korean dramas drive a global cultural wave.", "The DMZ is one of the most fortified borders.", "It went from war-torn to high-income in a generation."],
  KWT: ["Holds large oil reserves for its size.", "Its dinar is among the highest-valued currencies.", "Iraq's 1990 invasion triggered the Gulf War.", "The Kuwait Towers are a national landmark.", "Among the hottest inhabited places in summer."],
  LAO: ["Only landlocked country in Southeast Asia.", "Among the most heavily bombed countries in history.", "The Plain of Jars holds mysterious ancient stone vessels.", "Luang Prabang's temples make it a UNESCO town.", "The Mekong River is its lifeline."],
  LBN: ["Cedar trees feature on its flag.", "Beirut has been settled for over 5,000 years.", "Byblos is among the oldest inhabited cities.", "Government offices are shared among religious groups.", "Once called the 'Switzerland of the Middle East'."],
  LKA: ["Has two capitals near each other.", "A leading exporter of Ceylon tea.", "Sigiriya is an ancient rock fortress with frescoes.", "It was known as Ceylon until 1972.", "Cinnamon was prized from here in the spice trade."],
  MDV: ["World's lowest-lying country.", "A chain of about 1,200 coral islands.", "Resorts often occupy entire private islands.", "It held an underwater cabinet meeting in 2009.", "It has explored buying land against rising seas."],
  MMR: ["Moved its capital to planned Naypyidaw in 2005.", "Formerly known as Burma.", "Bagan's plain holds thousands of ancient temples.", "The Irrawaddy River runs the country's length.", "Thanaka paste is worn as sunblock and decoration."],
  MNG: ["World's most sparsely populated sovereign state.", "Genghis Khan founded its historic empire.", "The Gobi yields famous dinosaur fossils.", "Many still herd as nomads in gers.", "The Naadam festival features wrestling, archery, and racing."],
  MYS: ["Split between the Malay Peninsula and Borneo.", "The Petronas Towers were once the world's tallest.", "Borneo's rainforests are among Earth's oldest.", "Orangutans live wild only on Borneo and Sumatra.", "A blend of Malay, Chinese, and Indian heritage."],
  NPL: ["Home to Mount Everest, Earth's highest peak.", "The only country with a non-rectangular flag.", "Eight of the ten highest peaks lie on its borders.", "The Buddha was born at Lumbini here.", "It was never colonized by a European power."],
  OMN: ["Oldest independent state in the Arab world.", "Long famed for its frankincense.", "Its forts and falaj water channels are UNESCO-listed.", "It sits at the strategic Strait of Hormuz.", "Wahiba Sands offers classic desert dunes."],
  PAK: ["Home to K2, the second-highest mountain.", "The Indus Valley hosted an ancient civilization.", "The Karakoram Highway is among the highest paved roads.", "Mohenjo-daro was an ancient Indus city.", "The Khewra Salt Mine is one of the world's largest."],
  PHL: ["An archipelago of over 7,000 islands.", "Among the world's top coconut producers.", "The Banaue rice terraces were carved over millennia.", "Among the most typhoon-prone nations.", "Spanish then American rule shaped its languages."],
  PRK: ["One of the world's most isolated states.", "Uses its own Juche calendar.", "The Arirang Mass Games feature tens of thousands of performers.", "It is among the most militarized societies.", "The peninsula has been divided since 1945."],
  PSE: ["A partially recognized state in the West Bank and Gaza.", "Includes the ancient towns of Bethlehem and Jericho.", "Jericho is among the oldest inhabited cities on Earth.", "Bethlehem's Church of the Nativity is a UNESCO site.", "It holds non-member observer status at the UN."],
  QAT: ["First Arab nation to host the FIFA World Cup (2022).", "Among the highest GDP per capita.", "It built a metro and stadiums for the 2022 World Cup.", "Al Jazeera is based here.", "A mostly desert peninsula in the Persian Gulf."],
  SAU: ["Holds Islam's holiest cities, Mecca and Medina.", "Among the world's largest oil exporters.", "Millions perform the Hajj to Mecca each year.", "The Rub' al Khali is the largest continuous sand desert.", "It is building the linear city 'The Line'."],
  SGP: ["A city-state and one of the busiest ports.", "Rose from developing to high-income in a generation.", "One of only three surviving city-states.", "Famously bans the sale of chewing gum.", "Marina Bay Sands and Gardens by the Bay are landmarks."],
  SYR: ["Damascus is among the oldest inhabited cities.", "Site of the ancient ruins of Palmyra.", "Aleppo's old city was a major Silk Road hub.", "The Crac des Chevaliers is a famed Crusader castle.", "An early alphabet emerged at ancient Ugarit."],
  THA: ["Never colonized by a European power.", "Bangkok's full ceremonial name is the world's longest.", "The Grand Palace and reclining Buddha draw millions.", "Known for floating markets and street food.", "Historically called Siam."],
  TJK: ["Over 90% mountainous, dominated by the Pamirs.", "Home to one of the world's tallest dams.", "The Pamir Highway is among the world's highest roads.", "Tajik is closely related to Persian.", "It holds much of Central Asia's water."],
  TKM: ["The 'Door to Hell' gas crater has burned for decades.", "Mostly covered by the Karakum Desert.", "Ashgabat holds a record for white-marble buildings.", "Holds some of the world's largest gas reserves.", "The ancient Silk Road city of Merv lay here."],
  TLS: ["One of Asia's youngest nations (2002).", "Occupies half of the island of Timor.", "It restored independence after Indonesian occupation.", "Portuguese and Tetum are official languages.", "Coffee is a key export."],
  TUR: ["Straddles Europe and Asia.", "Istanbul is the only major city on two continents.", "The Hagia Sophia has been church, mosque, and museum.", "Cappadocia's 'fairy chimneys' draw balloon flights.", "Ancient Troy and Ephesus lie within its borders."],
  TWN: ["A disputed, self-governed island claimed by China.", "A global hub for semiconductor manufacturing.", "Taipei 101 was once the world's tallest building.", "It makes most of the world's most advanced chips.", "High mountains rise steeply from a dense coast."],
  UZB: ["One of only two doubly landlocked countries.", "Samarkand was a key Silk Road city.", "Samarkand's Registan is a jewel of Islamic architecture.", "Bukhara and Khiva are other Silk Road cities.", "A top cotton producer, at heavy cost to the Aral Sea."],
  VNM: ["One of the world's largest coffee exporters.", "Has a long, S-shaped coastline.", "Ha Long Bay's limestone islands are a UNESCO site.", "Motorbikes vastly outnumber cars.", "It reunified in 1975 after decades of war."],
  YEM: ["Socotra island has unique, alien-like flora.", "Among the oldest centers of human settlement.", "Shibam's towers are the 'Manhattan of the desert'.", "It was the legendary land of the Queen of Sheba.", "Mocha coffee is named for a Yemeni port."],
  // ---- Europe ----
  ALB: ["Dotted with thousands of communist-era bunkers.", "Was largely closed off under communist rule.", "Mother Teresa was of Albanian heritage.", "It has both Adriatic and Ionian coastlines.", "It is known for cross-faith religious tolerance."],
  AND: ["A Pyrenees microstate co-ruled by two princes.", "Has no airport or railway.", "Its co-princes are France's president and a Spanish bishop.", "It has one of the world's highest life expectancies.", "Skiing and duty-free shopping drive its economy."],
  AUT: ["Birthplace of Mozart and of psychoanalysis.", "Vienna often tops quality-of-life rankings.", "The Sound of Music was set in Salzburg.", "Vienna's coffeehouse culture is UNESCO-listed.", "The Alps cover much of the country."],
  BEL: ["Hosts the EU and NATO headquarters.", "Famous for waffles, chocolate, and beer.", "It once went over 18 months without a government.", "Comics like Tintin are a national art form.", "It has three official languages."],
  BGR: ["Produces a large share of the world's rose oil.", "Cyrillic script traces back to medieval Bulgaria.", "A head nod can mean 'no' and a shake 'yes'.", "The ancient Thracians left elaborate gold treasures.", "One of Europe's oldest states, founded in 681."],
  BIH: ["Mostar's Old Bridge is a famous landmark.", "A meeting point of Eastern and Western cultures.", "Sarajevo hosted the 1984 Winter Olympics.", "A 1914 assassination here helped spark WWI.", "It has a rotating three-member presidency."],
  BLR: ["One of Europe's most heavily forested countries.", "Landlocked in Eastern Europe.", "Its old-growth forest shelters the European bison.", "It was among the hardest hit by Chernobyl fallout.", "One of the last European states to use the death penalty."],
  CHE: ["Bern is the 'federal city', not a formal capital.", "Has four national languages.", "Famously neutral, it avoided both world wars.", "Geneva hosts the Red Cross and many UN agencies.", "CERN's collider straddles its French border."],
  CYP: ["An island divided since 1974.", "Mythological birthplace of Aphrodite.", "Nicosia is the last divided capital in Europe.", "Copper takes its name from the island.", "Its north remains outside effective control."],
  CZE: ["Among the highest beer consumption per capita.", "Prague Castle is one of the largest castle complexes.", "The word 'robot' was coined by a Czech writer.", "Prague's astronomical clock dates to the 15th century.", "It split peacefully from Slovakia in 1993."],
  DEU: ["Europe's largest economy.", "Stretches of the autobahn have no speed limit.", "It reunified in 1990 after the Berlin Wall fell.", "Munich's Oktoberfest is the world's largest folk festival.", "Gutenberg's printing press was invented here."],
  DNK: ["Often ranks among the world's happiest countries.", "Lego originated here.", "It flies the world's oldest continuously used flag.", "The cozy concept of 'hygge' comes from here.", "Greenland and the Faroe Islands are self-governing parts of the realm."],
  ESP: ["Has many UNESCO World Heritage cities.", "The midday siesta is a cultural tradition.", "Flamenco and its festivals are iconic.", "Gaudí's Sagrada Família has been built for over a century.", "Second only to Italy in UNESCO World Heritage Sites."],
  EST: ["A digital pioneer offering e-residency.", "Among the least religious countries.", "Most government services are available online.", "Its independence drive was a 'Singing Revolution'.", "Skype was built in part by Estonian engineers."],
  FIN: ["Has more saunas than cars per capita.", "Often ranked the world's happiest country.", "The northern lights shine across its far north.", "Santa Claus is marketed as living in its Lapland.", "Its schools are studied worldwide."],
  FRA: ["The world's most visited country by tourists.", "The metric system originated here.", "The Eiffel Tower was built for the 1889 World's Fair.", "The Louvre is the world's most visited museum.", "Its overseas territories span the most time zones of any country."],
  GBR: ["A union of four nations.", "The Greenwich meridian anchors global time.", "The Industrial Revolution began here.", "It has no single written constitution.", "The London Underground is the world's oldest metro."],
  GRC: ["Birthplace of democracy and the Olympics.", "Has thousands of islands.", "The Parthenon crowns the Acropolis.", "Western philosophy traces to its thinkers.", "It has thousands of islands."],
  HRV: ["Has over a thousand Adriatic islands.", "The necktie originated here.", "Dubrovnik's walled city is a famous filming site.", "Plitvice Lakes cascade through terraced falls.", "The Dalmatian dog is named for its coast."],
  HUN: ["Its language is unrelated to its neighbors'.", "Budapest sits on famous thermal springs.", "The Rubik's Cube was invented here.", "Budapest united Buda and Pest across the Danube.", "It has produced many Nobel laureates."],
  IRL: ["Known as the 'Emerald Isle'.", "Has no native snakes.", "St. Patrick's Day is celebrated worldwide.", "Its writers include Joyce, Yeats, and Beckett.", "The Cliffs of Moher drop into the Atlantic."],
  ISL: ["Runs largely on geothermal and hydro power.", "Has no mosquitoes.", "It straddles two tectonic plates.", "The Althing is among the oldest parliaments.", "It has no standing army."],
  ITA: ["Has the most UNESCO World Heritage Sites.", "Surrounds two microstates within its borders.", "Rome's Colosseum and the Vatican draw millions.", "The Renaissance flourished in Florence and beyond.", "Pizza and pasta are global exports."],
  LIE: ["A doubly landlocked microstate.", "A surprising major producer of false teeth.", "Named after the family that rules it.", "It has no military and a very high GDP per capita.", "It once famously offered itself for rent as a venue."],
  LTU: ["Last pagan state in Europe to adopt Christianity.", "Once one of Europe's largest medieval states.", "The Hill of Crosses holds hundreds of thousands of crosses.", "It was the first Soviet republic to declare independence.", "Basketball is close to a national religion."],
  LUX: ["Among the world's highest GDP per capita.", "Made nationwide public transport free.", "A founding EU member and institutional seat.", "The world's only remaining grand duchy.", "Trilingual in Luxembourgish, French, and German."],
  LVA: ["Riga has Europe's densest Art Nouveau architecture.", "Heavily forested.", "Riga was a powerful Hanseatic trading city.", "It shares Baltic midsummer traditions.", "It regained independence from the USSR in 1991."],
  MCO: ["World's second-smallest and densest country.", "Hosts a famous Formula 1 street race.", "The Monte Carlo casino is world-famous.", "Its residents pay no income tax.", "The Grimaldi family has ruled for over 700 years."],
  MDA: ["One of the world's least-visited countries.", "Has some of the largest wine cellars on Earth.", "Mileștii Mici holds a vast wine collection.", "The breakaway Transnistria lies outside its control.", "Among Europe's least urbanized countries."],
  MKD: ["Renamed from Macedonia in 2019.", "Lake Ohrid is among Europe's oldest, deepest lakes.", "Mother Teresa was born in Skopje.", "It renamed to settle a dispute with Greece.", "Landlocked in the heart of the Balkans."],
  MLT: ["One of the smallest, densest countries.", "Has megalithic temples older than the pyramids.", "St. John's Co-Cathedral holds a famous Caravaggio.", "It withstood the Great Siege of 1565.", "English and Maltese are both official."],
  MNE: ["Its name means 'Black Mountain'.", "Became independent from Serbia in 2006.", "The Bay of Kotor is a dramatic fjord-like inlet.", "It uses the euro without being in the eurozone.", "Durmitor is a national park and UNESCO site."],
  NLD: ["Much of the land lies below sea level.", "Amsterdam is the capital; government sits in The Hague.", "The Hague hosts the International Court of Justice.", "A cycling leader, with bikes outnumbering people.", "It reclaimed vast land via polders and dikes."],
  NOR: ["Famous for deep, glacier-carved fjords.", "The midnight sun shines in its far north.", "It runs one of the world's largest sovereign wealth funds.", "The Nobel Peace Prize is awarded in Oslo.", "Most of its power is hydroelectric."],
  POL: ["Birthplace of Copernicus and Marie Curie.", "Has Europe's largest surviving primeval forest.", "Wieliczka salt mine has chapels carved in salt.", "Warsaw was largely rebuilt after WWII.", "Auschwitz, a somber memorial, lies in its south."],
  PRT: ["One of Europe's oldest stable nation-states.", "Pioneered the Age of Exploration.", "Explorers like Vasco da Gama opened sea routes to Asia.", "Port wine is named for the city of Porto.", "It once ruled an empire from Brazil to Macau."],
  ROU: ["Home to Transylvania and the Dracula legend.", "The Carpathian Mountains sweep through it.", "The Palace of the Parliament is among Earth's largest buildings.", "Romanian is a Romance language amid Slavic neighbors.", "The Danube Delta is a vast wildlife wetland."],
  RUS: ["Largest country in the world by area.", "Spans eleven time zones.", "Lake Baikal is the deepest, oldest freshwater lake.", "The Trans-Siberian is the world's longest railway.", "The Hermitage is among the great museums."],
  SMR: ["Claims to be the oldest surviving republic.", "Entirely surrounded by Italy.", "Founded by tradition in the year 301.", "Perched atop Monte Titano with medieval towers.", "It has two heads of state serving six-month terms."],
  SRB: ["A landlocked Balkan country on the Danube.", "Belgrade is one of Europe's oldest cities.", "Inventor Nikola Tesla is honored across the country.", "Raspberry exports are a surprising strength.", "It was the core of former Yugoslavia."],
  SVK: ["Among the most castles per capita.", "The High Tatras rise along its northern border.", "Among the most castles per capita in the world.", "Bratislava is the only capital bordering two countries.", "It split peacefully from Czechia in 1993."],
  SVN: ["More than half the country is forested.", "Lake Bled is a postcard landmark.", "Postojna Cave hosts the rare 'human fish' olm.", "First former Yugoslav republic to join the EU.", "The Julian Alps include its peak, Triglav."],
  SWE: ["Pioneered the modern ombudsman office.", "Has the most islands of any country.", "The Nobel Prizes (except Peace) are awarded in Stockholm.", "IKEA, Spotify, and ABBA are cultural exports.", "Long neutral, it recently joined NATO."],
  UKR: ["Largest country entirely within Europe.", "Long known as the 'breadbasket of Europe'.", "The Chernobyl exclusion zone lies in its north.", "Kyiv is one of Eastern Europe's oldest cities.", "Its black 'chernozem' soil is prized for farming."],
  UNK: ["Declared independence in 2008; recognition is disputed.", "Among Europe's youngest populations by median age.", "Its much-debated National Library is a Pristina landmark.", "The 'Newborn' monument was unveiled at independence.", "It uses the euro without being in the eurozone."],
  VAT: ["Smallest sovereign state by area and population.", "Issues its own euro coins.", "Michelangelo painted the Sistine Chapel ceiling.", "St. Peter's is among the largest churches in the world.", "The Swiss Guard protects the pope in Renaissance uniforms."],
  // ---- Oceania ----
  AUS: ["The only nation that is also a continent.", "Canberra was a compromise capital between Sydney and Melbourne.", "The Great Barrier Reef is the largest living structure on Earth.", "Uluru is a vast sacred desert monolith.", "It has unique animals like kangaroos and koalas."],
  FJI: ["An archipelago of more than 300 islands.", "Rugby is the national passion.", "Built mainly around two large volcanic islands.", "Kava is central to social ceremony.", "Its waters are renowned for soft-coral diving."],
  FSM: ["Spread across hundreds of Pacific islands.", "Includes the ancient stone city of Nan Madol.", "Nan Madol was built on a network of artificial islets.", "A federation of four island states.", "It is in free association with the United States."],
  KIR: ["Straddles the equator and the date line.", "Among the first nations to greet the new year.", "It spans all four hemispheres.", "Rising seas threaten its low atolls.", "It bought land in Fiji as a potential refuge."],
  MHL: ["Site of Cold War nuclear tests at Bikini Atoll.", "A nation of low-lying coral atolls.", "Traditional 'stick charts' guided ocean navigation.", "In free association with the United States.", "Nuclear testing left lasting effects on some atolls."],
  NRU: ["World's smallest island nation.", "Its economy once rested on phosphate mining.", "It has no official capital, only districts.", "Phosphate mining stripped much of its interior.", "Among the least-visited countries in the world."],
  NZL: ["First country to give women the vote (1893).", "Has far more sheep than people.", "The Lord of the Rings films showcased its landscapes.", "The Māori haka is performed before rugby matches.", "It has no native land snakes."],
  PLW: ["Created the world's first shark sanctuary.", "Famous for its Jellyfish Lake.", "Swimmers float among harmless jellyfish in a marine lake.", "First nation to ban reef-toxic sunscreens.", "Its Rock Islands are a UNESCO site."],
  PNG: ["Among the most linguistically diverse countries.", "Shares the island of New Guinea with Indonesia.", "One of the least-explored regions for biodiversity.", "The bird-of-paradise is a national symbol.", "Some communities had little outside contact until the 1900s."],
  SLB: ["Site of major WWII Pacific battles.", "An archipelago of nearly a thousand islands.", "Guadalcanal saw a pivotal WWII campaign.", "Some lagoons glow with bioluminescence.", "Among the most linguistically diverse nations."],
  TON: ["The only Pacific nation never formally colonized.", "A constitutional monarchy.", "A huge 2022 underwater eruption was heard far away.", "Sometimes called the 'Friendly Islands'.", "Humpback whale-watching is a major draw."],
  TUV: ["One of the smallest, lowest-lying nations.", "Earns income from its '.tv' internet domain.", "Among the smallest and least-visited UN members.", "Building a 'digital nation' against sea-level rise.", "Made up of nine tiny atolls and islands."],
  VUT: ["Often ranked among the happiest nations.", "Home to highly active volcanoes.", "Mount Yasur is a very accessible active volcano.", "Vine land-diving inspired modern bungee jumping.", "Pentecost Island's ritual is performed yearly."],
  WSM: ["Switched the side of the road it drives on in 2009.", "Jumped the international date line in 2011.", "Author Robert Louis Stevenson spent his final years here.", "The fa'a Samoa guides communal life.", "The To Sua ocean trench is a famous swimming hole."],
};

// Multi-capital countries: full list with types + which one is the guessable primary.
const capitalOverrides = {
  ZAF: { primary: "Pretoria", list: [
    { name: "Pretoria", type: "executive" },
    { name: "Cape Town", type: "legislative" },
    { name: "Bloemfontein", type: "judicial" } ] },
  BOL: { primary: "La Paz", list: [
    { name: "La Paz", type: "administrative (seat of government)" },
    { name: "Sucre", type: "constitutional" } ] },
  LKA: { primary: "Sri Jayawardenepura Kotte", list: [
    { name: "Sri Jayawardenepura Kotte", type: "official (legislative)" },
    { name: "Colombo", type: "commercial (executive)" } ] },
  SWZ: { primary: "Mbabane", list: [
    { name: "Mbabane", type: "administrative" },
    { name: "Lobamba", type: "legislative / royal" } ] },
  NLD: { primary: "Amsterdam", list: [
    { name: "Amsterdam", type: "constitutional capital" },
    { name: "The Hague", type: "seat of government" } ] },
  CIV: { primary: "Yamoussoukro", list: [
    { name: "Yamoussoukro", type: "official" },
    { name: "Abidjan", type: "economic (de facto)" } ] },
  BEN: { primary: "Porto-Novo", list: [
    { name: "Porto-Novo", type: "official" },
    { name: "Cotonou", type: "seat of government" } ] },
};

// Accepted-name aliases for fuzzy answer-checking (beyond common/official/altSpellings).
const nameAliasOverrides = {
  USA: ["USA", "US", "America", "United States of America"],
  GBR: ["UK", "Britain", "Great Britain", "United Kingdom of Great Britain and Northern Ireland"],
  CZE: ["Czech Republic", "Czechia"],
  COD: ["DRC", "Democratic Republic of the Congo", "Congo-Kinshasa", "DR Congo"],
  COG: ["Republic of the Congo", "Congo-Brazzaville", "Congo Republic"],
  CIV: ["Ivory Coast", "Cote d'Ivoire", "Cote dIvoire"],
  MMR: ["Myanmar", "Burma"],
  TUR: ["Turkey", "Turkiye"],
  KOR: ["South Korea", "Republic of Korea"],
  PRK: ["North Korea", "DPRK"],
  RUS: ["Russia", "Russian Federation"],
  SWZ: ["Eswatini", "Swaziland"],
  MKD: ["North Macedonia", "Macedonia"],
  TLS: ["Timor-Leste", "East Timor"],
  CPV: ["Cape Verde", "Cabo Verde"],
  VAT: ["Vatican", "Vatican City", "Holy See"],
  NLD: ["Netherlands", "Holland"],
  ARE: ["UAE", "United Arab Emirates", "Emirates"],
  STP: ["Sao Tome and Principe", "Sao Tome"],
};

// Extra accepted capital spellings (romanization variants, old names).
const capitalAliasOverrides = {
  UKR: ["Kyiv", "Kiev"],
  IND: ["New Delhi", "Delhi"],
  USA: ["Washington", "Washington DC", "Washington D.C."],
  CHN: ["Beijing", "Peking"],
  MMR: ["Naypyidaw", "Nay Pyi Taw"],
  KAZ: ["Astana", "Nur-Sultan"],
  VNM: ["Hanoi", "Ha Noi"],
  ESH: ["El Aaiún", "El Aaiun", "Laayoune"],
  GRD: ["St. George's", "Saint George's"],
  VUT: ["Port Vila", "Port-Vila"],
  YEM: ["Sana'a", "Sanaa"],
  KIR: ["South Tarawa", "Tarawa"],
};

// Country populations absent/unmatched in the samayo dataset (approximate, ~2018-2020 era).
const popHardcode = { FJI: 889953, FSM: 112640, VAT: 825, TWN: 23570000, UNK: 1795000 };

// samayo population dataset uses names that won't auto-match; map name -> ISO3.
const popNameOverrides = {
  "United States": "USA", "Czech Republic": "CZE", "Czechia": "CZE",
  "Democratic Republic of the Congo": "COD", "Congo (Dem. Rep.)": "COD", "DR Congo": "COD",
  "Republic of the Congo": "COG", "Congo": "COG", "Congo (Rep.)": "COG",
  "Ivory Coast": "CIV", "Cote d'Ivoire": "CIV", "Côte d'Ivoire": "CIV",
  "Myanmar": "MMR", "Burma": "MMR", "Russia": "RUS", "Russian Federation": "RUS",
  "South Korea": "KOR", "Korea South": "KOR", "North Korea": "PRK", "Korea North": "PRK",
  "Turkey": "TUR", "Turkiye": "TUR", "Cape Verde": "CPV", "Cabo Verde": "CPV",
  "Swaziland": "SWZ", "Eswatini": "SWZ", "Macedonia": "MKD", "North Macedonia": "MKD",
  "East Timor": "TLS", "Timor-Leste": "TLS", "Vatican City": "VAT", "Holy See": "VAT",
  "Palestinian Territory": "PSE", "Palestine": "PSE", "Brunei": "BRN", "Laos": "LAO",
  "Syria": "SYR", "Vietnam": "VNM", "Iran": "IRN", "Tanzania": "TZA", "Bolivia": "BOL",
  "Venezuela": "VEN", "Moldova": "MDA", "The Gambia": "GMB", "Gambia": "GMB",
  "Sao Tome and Principe": "STP", "Kosovo": "UNK", "Taiwan": "TWN", "Western Sahara": "ESH",
  "United Kingdom": "GBR", "United Arab Emirates": "ARE", "Saint Kitts and Nevis": "KNA",
  "Saint Vincent and the Grenadines": "VCT", "Micronesia": "FSM", "Netherlands": "NLD",
};

// Wikipedia article per country (canonical titles; redirects cover variants).
const wikipedia = {
  AFG: "https://en.wikipedia.org/wiki/Afghanistan",
  AGO: "https://en.wikipedia.org/wiki/Angola",
  ALB: "https://en.wikipedia.org/wiki/Albania",
  AND: "https://en.wikipedia.org/wiki/Andorra",
  ARE: "https://en.wikipedia.org/wiki/United_Arab_Emirates",
  ARG: "https://en.wikipedia.org/wiki/Argentina",
  ARM: "https://en.wikipedia.org/wiki/Armenia",
  ATG: "https://en.wikipedia.org/wiki/Antigua_and_Barbuda",
  AUS: "https://en.wikipedia.org/wiki/Australia",
  AUT: "https://en.wikipedia.org/wiki/Austria",
  AZE: "https://en.wikipedia.org/wiki/Azerbaijan",
  BDI: "https://en.wikipedia.org/wiki/Burundi",
  BEL: "https://en.wikipedia.org/wiki/Belgium",
  BEN: "https://en.wikipedia.org/wiki/Benin",
  BFA: "https://en.wikipedia.org/wiki/Burkina_Faso",
  BGD: "https://en.wikipedia.org/wiki/Bangladesh",
  BGR: "https://en.wikipedia.org/wiki/Bulgaria",
  BHR: "https://en.wikipedia.org/wiki/Bahrain",
  BHS: "https://en.wikipedia.org/wiki/Bahamas",
  BIH: "https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina",
  BLR: "https://en.wikipedia.org/wiki/Belarus",
  BLZ: "https://en.wikipedia.org/wiki/Belize",
  BOL: "https://en.wikipedia.org/wiki/Bolivia",
  BRA: "https://en.wikipedia.org/wiki/Brazil",
  BRB: "https://en.wikipedia.org/wiki/Barbados",
  BRN: "https://en.wikipedia.org/wiki/Brunei",
  BTN: "https://en.wikipedia.org/wiki/Bhutan",
  BWA: "https://en.wikipedia.org/wiki/Botswana",
  CAF: "https://en.wikipedia.org/wiki/Central_African_Republic",
  CAN: "https://en.wikipedia.org/wiki/Canada",
  CHE: "https://en.wikipedia.org/wiki/Switzerland",
  CHL: "https://en.wikipedia.org/wiki/Chile",
  CHN: "https://en.wikipedia.org/wiki/China",
  CIV: "https://en.wikipedia.org/wiki/Ivory_Coast",
  CMR: "https://en.wikipedia.org/wiki/Cameroon",
  COD: "https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo",
  COG: "https://en.wikipedia.org/wiki/Republic_of_the_Congo",
  COL: "https://en.wikipedia.org/wiki/Colombia",
  COM: "https://en.wikipedia.org/wiki/Comoros",
  CPV: "https://en.wikipedia.org/wiki/Cape_Verde",
  CRI: "https://en.wikipedia.org/wiki/Costa_Rica",
  CUB: "https://en.wikipedia.org/wiki/Cuba",
  CYP: "https://en.wikipedia.org/wiki/Cyprus",
  CZE: "https://en.wikipedia.org/wiki/Czech_Republic",
  DEU: "https://en.wikipedia.org/wiki/Germany",
  DJI: "https://en.wikipedia.org/wiki/Djibouti",
  DMA: "https://en.wikipedia.org/wiki/Dominica",
  DNK: "https://en.wikipedia.org/wiki/Denmark",
  DOM: "https://en.wikipedia.org/wiki/Dominican_Republic",
  DZA: "https://en.wikipedia.org/wiki/Algeria",
  ECU: "https://en.wikipedia.org/wiki/Ecuador",
  EGY: "https://en.wikipedia.org/wiki/Egypt",
  ERI: "https://en.wikipedia.org/wiki/Eritrea",
  ESH: "https://en.wikipedia.org/wiki/Western_Sahara",
  ESP: "https://en.wikipedia.org/wiki/Spain",
  EST: "https://en.wikipedia.org/wiki/Estonia",
  ETH: "https://en.wikipedia.org/wiki/Ethiopia",
  FIN: "https://en.wikipedia.org/wiki/Finland",
  FJI: "https://en.wikipedia.org/wiki/Fiji",
  FRA: "https://en.wikipedia.org/wiki/France",
  FSM: "https://en.wikipedia.org/wiki/Micronesia",
  GAB: "https://en.wikipedia.org/wiki/Gabon",
  GBR: "https://en.wikipedia.org/wiki/United_Kingdom",
  GEO: "https://en.wikipedia.org/wiki/Georgia",
  GHA: "https://en.wikipedia.org/wiki/Ghana",
  GIN: "https://en.wikipedia.org/wiki/Guinea",
  GMB: "https://en.wikipedia.org/wiki/Gambia",
  GNB: "https://en.wikipedia.org/wiki/Guinea-Bissau",
  GNQ: "https://en.wikipedia.org/wiki/Equatorial_Guinea",
  GRC: "https://en.wikipedia.org/wiki/Greece",
  GRD: "https://en.wikipedia.org/wiki/Grenada",
  GTM: "https://en.wikipedia.org/wiki/Guatemala",
  GUY: "https://en.wikipedia.org/wiki/Guyana",
  HND: "https://en.wikipedia.org/wiki/Honduras",
  HRV: "https://en.wikipedia.org/wiki/Croatia",
  HTI: "https://en.wikipedia.org/wiki/Haiti",
  HUN: "https://en.wikipedia.org/wiki/Hungary",
  IDN: "https://en.wikipedia.org/wiki/Indonesia",
  IND: "https://en.wikipedia.org/wiki/India",
  IRL: "https://en.wikipedia.org/wiki/Ireland",
  IRN: "https://en.wikipedia.org/wiki/Iran",
  IRQ: "https://en.wikipedia.org/wiki/Iraq",
  ISL: "https://en.wikipedia.org/wiki/Iceland",
  ISR: "https://en.wikipedia.org/wiki/Israel",
  ITA: "https://en.wikipedia.org/wiki/Italy",
  JAM: "https://en.wikipedia.org/wiki/Jamaica",
  JOR: "https://en.wikipedia.org/wiki/Jordan",
  JPN: "https://en.wikipedia.org/wiki/Japan",
  KAZ: "https://en.wikipedia.org/wiki/Kazakhstan",
  KEN: "https://en.wikipedia.org/wiki/Kenya",
  KGZ: "https://en.wikipedia.org/wiki/Kyrgyzstan",
  KHM: "https://en.wikipedia.org/wiki/Cambodia",
  KIR: "https://en.wikipedia.org/wiki/Kiribati",
  KNA: "https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis",
  KOR: "https://en.wikipedia.org/wiki/South_Korea",
  KWT: "https://en.wikipedia.org/wiki/Kuwait",
  LAO: "https://en.wikipedia.org/wiki/Laos",
  LBN: "https://en.wikipedia.org/wiki/Lebanon",
  LBR: "https://en.wikipedia.org/wiki/Liberia",
  LBY: "https://en.wikipedia.org/wiki/Libya",
  LCA: "https://en.wikipedia.org/wiki/Saint_Lucia",
  LIE: "https://en.wikipedia.org/wiki/Liechtenstein",
  LKA: "https://en.wikipedia.org/wiki/Sri_Lanka",
  LSO: "https://en.wikipedia.org/wiki/Lesotho",
  LTU: "https://en.wikipedia.org/wiki/Lithuania",
  LUX: "https://en.wikipedia.org/wiki/Luxembourg",
  LVA: "https://en.wikipedia.org/wiki/Latvia",
  MAR: "https://en.wikipedia.org/wiki/Morocco",
  MCO: "https://en.wikipedia.org/wiki/Monaco",
  MDA: "https://en.wikipedia.org/wiki/Moldova",
  MDG: "https://en.wikipedia.org/wiki/Madagascar",
  MDV: "https://en.wikipedia.org/wiki/Maldives",
  MEX: "https://en.wikipedia.org/wiki/Mexico",
  MHL: "https://en.wikipedia.org/wiki/Marshall_Islands",
  MKD: "https://en.wikipedia.org/wiki/North_Macedonia",
  MLI: "https://en.wikipedia.org/wiki/Mali",
  MLT: "https://en.wikipedia.org/wiki/Malta",
  MMR: "https://en.wikipedia.org/wiki/Myanmar",
  MNE: "https://en.wikipedia.org/wiki/Montenegro",
  MNG: "https://en.wikipedia.org/wiki/Mongolia",
  MOZ: "https://en.wikipedia.org/wiki/Mozambique",
  MRT: "https://en.wikipedia.org/wiki/Mauritania",
  MUS: "https://en.wikipedia.org/wiki/Mauritius",
  MWI: "https://en.wikipedia.org/wiki/Malawi",
  MYS: "https://en.wikipedia.org/wiki/Malaysia",
  NAM: "https://en.wikipedia.org/wiki/Namibia",
  NER: "https://en.wikipedia.org/wiki/Niger",
  NGA: "https://en.wikipedia.org/wiki/Nigeria",
  NIC: "https://en.wikipedia.org/wiki/Nicaragua",
  NLD: "https://en.wikipedia.org/wiki/Netherlands",
  NOR: "https://en.wikipedia.org/wiki/Norway",
  NPL: "https://en.wikipedia.org/wiki/Nepal",
  NRU: "https://en.wikipedia.org/wiki/Nauru",
  NZL: "https://en.wikipedia.org/wiki/New_Zealand",
  OMN: "https://en.wikipedia.org/wiki/Oman",
  PAK: "https://en.wikipedia.org/wiki/Pakistan",
  PAN: "https://en.wikipedia.org/wiki/Panama",
  PER: "https://en.wikipedia.org/wiki/Peru",
  PHL: "https://en.wikipedia.org/wiki/Philippines",
  PLW: "https://en.wikipedia.org/wiki/Palau",
  PNG: "https://en.wikipedia.org/wiki/Papua_New_Guinea",
  POL: "https://en.wikipedia.org/wiki/Poland",
  PRK: "https://en.wikipedia.org/wiki/North_Korea",
  PRT: "https://en.wikipedia.org/wiki/Portugal",
  PRY: "https://en.wikipedia.org/wiki/Paraguay",
  PSE: "https://en.wikipedia.org/wiki/State_of_Palestine",
  QAT: "https://en.wikipedia.org/wiki/Qatar",
  ROU: "https://en.wikipedia.org/wiki/Romania",
  RUS: "https://en.wikipedia.org/wiki/Russia",
  RWA: "https://en.wikipedia.org/wiki/Rwanda",
  SAU: "https://en.wikipedia.org/wiki/Saudi_Arabia",
  SDN: "https://en.wikipedia.org/wiki/Sudan",
  SEN: "https://en.wikipedia.org/wiki/Senegal",
  SGP: "https://en.wikipedia.org/wiki/Singapore",
  SLB: "https://en.wikipedia.org/wiki/Solomon_Islands",
  SLE: "https://en.wikipedia.org/wiki/Sierra_Leone",
  SLV: "https://en.wikipedia.org/wiki/El_Salvador",
  SMR: "https://en.wikipedia.org/wiki/San_Marino",
  SOM: "https://en.wikipedia.org/wiki/Somalia",
  SRB: "https://en.wikipedia.org/wiki/Serbia",
  SSD: "https://en.wikipedia.org/wiki/South_Sudan",
  STP: "https://en.wikipedia.org/wiki/São_Tomé_and_Príncipe",
  SUR: "https://en.wikipedia.org/wiki/Suriname",
  SVK: "https://en.wikipedia.org/wiki/Slovakia",
  SVN: "https://en.wikipedia.org/wiki/Slovenia",
  SWE: "https://en.wikipedia.org/wiki/Sweden",
  SWZ: "https://en.wikipedia.org/wiki/Eswatini",
  SYC: "https://en.wikipedia.org/wiki/Seychelles",
  SYR: "https://en.wikipedia.org/wiki/Syria",
  TCD: "https://en.wikipedia.org/wiki/Chad",
  TGO: "https://en.wikipedia.org/wiki/Togo",
  THA: "https://en.wikipedia.org/wiki/Thailand",
  TJK: "https://en.wikipedia.org/wiki/Tajikistan",
  TKM: "https://en.wikipedia.org/wiki/Turkmenistan",
  TLS: "https://en.wikipedia.org/wiki/East_Timor",
  TON: "https://en.wikipedia.org/wiki/Tonga",
  TTO: "https://en.wikipedia.org/wiki/Trinidad_and_Tobago",
  TUN: "https://en.wikipedia.org/wiki/Tunisia",
  TUR: "https://en.wikipedia.org/wiki/Turkey",
  TUV: "https://en.wikipedia.org/wiki/Tuvalu",
  TWN: "https://en.wikipedia.org/wiki/Taiwan",
  TZA: "https://en.wikipedia.org/wiki/Tanzania",
  UGA: "https://en.wikipedia.org/wiki/Uganda",
  UKR: "https://en.wikipedia.org/wiki/Ukraine",
  UNK: "https://en.wikipedia.org/wiki/Kosovo",
  URY: "https://en.wikipedia.org/wiki/Uruguay",
  USA: "https://en.wikipedia.org/wiki/United_States",
  UZB: "https://en.wikipedia.org/wiki/Uzbekistan",
  VAT: "https://en.wikipedia.org/wiki/Vatican_City",
  VCT: "https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines",
  VEN: "https://en.wikipedia.org/wiki/Venezuela",
  VNM: "https://en.wikipedia.org/wiki/Vietnam",
  VUT: "https://en.wikipedia.org/wiki/Vanuatu",
  WSM: "https://en.wikipedia.org/wiki/Samoa",
  YEM: "https://en.wikipedia.org/wiki/Yemen",
  ZAF: "https://en.wikipedia.org/wiki/South_Africa",
  ZMB: "https://en.wikipedia.org/wiki/Zambia",
  ZWE: "https://en.wikipedia.org/wiki/Zimbabwe",
};

module.exports = { trivia, wikipedia, capitalOverrides, nameAliasOverrides, capitalAliasOverrides, popNameOverrides, popHardcode };
